# blob doesn't exist 404
DELETE http://localhost:1337/api/jsonblob/556433310504
Content-Type: application/json

###
# invalid url Bad Req
DELETE http://localhost:1337/api/jsonblob/556433dfa310504
Content-Type: application/json

###
# short url Bad Req
DELETE http://localhost:1337/api/jsonblob/43
Content-Type: application/json

###
# invalid content type, unsupported media type
DELETE http://localhost:1337/api/jsonblob/556433310504
Content-Type: application/javascript